### ISSUE TITLE
SigV4 returns wrong error for mismatched date and signed-date

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/lakeFS#2465]
When the date in the signed credentials on a SigV4 request does not match the date (or x-amz-date) on the message we return `...`.

In fact we should return an explanatory `SignatureDoesNotMatch`.  See https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html, starting with text:

> The date that you use as part of the credential must match the date value in the `x-amz-date` header.

**Comment by arielshaqed** [comment]
Still an error, and users will have a harder time debugging some integrations.

**Comment by N-o-Z** [comment]
@zubron was this fixed in your latest PR?

**Comment by zubron** [comment]
@N-o-Z No, my PR didn't change the error values returned from `getAmzDate`. This is still an issue.
